services:
  disque:
    # image: richnorth/disque
    build: ./disque/
    ports:
      - "7711:7711"

  disque-other:
    build: ./disque/

  worker-no-ls:
    build: .
    command: ["dwqw", "-D", "disque:7711", "--jobs", "3", "--exclude", "ls.*"]
    environment:
      - PYTHONUNBUFFERED=1

  worker-else:
    build: .
    command: ["dwqw", "-D", "disque-other:7711", "--jobs", "3"]
    environment:
      - PYTHONUNBUFFERED=1
